config/routes.rb
Rails.application.routes.draw do
  resources :characters do
    collection do
      get 'view', to: 'characters#view', as: :view
    end
  end
  resources :guilds

  get '/characters/challenge_mode/:id', to: 'characters#challenge_mode', as: :challenge_mode
  get '/characters/pets_mounts/:id', to: 'characters#pets_mounts', as: :pets_mounts
  get '/characters/achievements/:id', to: 'characters#achievements', as: :achievements
  get '/characters/progression/:id', to: 'characters#progression', as: :progression
  get '/characters/reputation/:id', to: 'characters#reputation', as: :reputation

  root to: 'visitors#index'
end

app/models/concerns/mock_model.rb
require 'active_support/concern'

module MockModel
  extend ActiveSupport::Concern

  included do
    include ActiveModel::Conversion
    include ActiveModel::Validations
    include ActiveModel::MassAssignmentSecurity
  end

  def initialize(attributes = {})
    assign_attributes(attributes)
    yield(self) if block_given?
  end

  def persisted?
    false
  end

  def assign_attributes(values, options = {})
    sanitize_for_mass_assignment(values, options[:as]).each do |k, v|
      send("#{k}=", v)
    end
  end
end

app/models/search.rb
class Search
  TRUE_VALUES = ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES

  include MockModel

  attr_accessor :character_name, :realm

  validates :query, presence: true
end

app/controllers/characters_controller.rb
require 'battle-muffin'
require 'date'

class CharactersController < ApplicationController
  helper_method :build_stats_string, :get_race, :get_background, :get_profile_main, :get_guild, :get_item_url, :name,  :average_item_level, :average_item_level_equipped, :achievement_points, :get_item_id, :get_icon_url, :achievement_array, :get_standing
  before_action :load_data, only: [:view, :challenge_mode, :pets_mounts, :achievements, :progression, :reputation]

  def index
    #
  end

  def view
    #
  end

  def challenge_mode
    #
  end

  def pets_mounts
    #
  end

  def achievements
    #
  end

  def progression 
    #
  end

  def reputation 
    #
  end


  def get_current_title(titles)
    titles.each do |title|
      if title['selected']
        replacements = [ ["%s, ", ""], ["%s ", ""], [" %s", "" ] ]
        replacements.each {|replacement| title['name'].gsub!(replacement[0], replacement[1])}
        return title['name']
      end
    end
    return ""
  end

  def build_stats_string
    "#{@character.level} #{get_race} #{talent_specialization} #{get_class(@character.class)}, #{@realm}"
  end

  def get_race
    @races.each do |race|
      return race['name'] if race['id'] == @character.race
    end
  end

  def get_class(class_id)
    @classes.each do |character_class|
      return character_class['name'] if character_class['id'] == class_id
    end
  end

  def talent_specialization
    @all_info['talents'].each do |spec|
      return spec['spec']['name'] if spec['selected']
    end
  end

  def get_background
    "http://us.battle.net/wow/static/images/character/summary/backgrounds/race/#{@character.race}.jpg"
  end

  def get_profile_main
    "http://us.battle.net/static-render/us/#{@character.thumbnail.gsub!("avatar", "profilemain")}"
  end

  def get_guild
    begin
      @all_info['guild']['name']
    rescue
      ""
    end
  end

  def get_item_id(slot)
    @items[slot]['id'] unless @items[slot].nil?
  end

  def get_item_url(slot)
    begin
      "http://media.blizzard.com/wow/icons/56/#{@items[slot]['icon']}.jpg"
    rescue
      if slot == "mainHand" || slot == "offHand"
        "empty_weapon.png"
      else
        "blank_item_slot.png"
      end
    end
  end

  def get_icon_url(name)
    "http://media.blizzard.com/wow/icons/56/#{name}.jpg"
  end


  def name
    @character.name
  end

  def average_item_level
    @all_info['items']['averageItemLevel']
  end

  def average_item_level_equipped
    @all_info['items']['averageItemLevelEquipped']
  end

  def achievement_points
    @all_info['achievementPoints']
  end

  def achievement_array
    achieves = [ ]
    @all_info['achievements']['achievementsCompleted'].reverse.first(25).each_with_index do |ach, index|
      tmp = { }
      tmp[:id] = ach
      tmp[:time] = get_achieve_timestamp(index)
      tmp[:name] = get_achievement(ach)
      tmp[:timestamp] = get_achieve_timestamp(index)
      achieves << tmp
    end
    achieves.sort_by { |hsh| hsh[:time] }.reverse
  end

  def get_achievement(ach)
    get_achievement_name(ach)
  end


  def get_achieve_timestamp(index)
    timestamp = @all_info['achievements']['achievementsCompletedTimestamp'][index]
    DateTime.strptime(timestamp.to_s,'%Q').strftime("%c")
  end

  def get_achievement_name(id)
    Nokogiri::HTML(HTTParty.get("http://www.wowhead.com/achievement=#{id}")).title.split("- Achievement").first.strip
  end

  def load_data
    @client             = BattleMuffin.new("7argtwb4rtuy2ccwcfjs74eapm52juhv") 
    char_name           = params[:character][:name].capitalize
    @realm              = params[:character][:realm]
    @realms             = get_realms
    @character          = @client.character_handler.search(@realm, char_name) 
    @all_info           = @character.all_info
    @items              = @all_info['items']
    @title              = get_current_title(@all_info['titles'])
    @races              = JSON.parse(File.read('app/helpers/races.json'))['races']
    @classes            = JSON.parse(File.read('app/helpers/classes.json'))['classes']
    @left_column_gear   = ["head", "neck", "shoulder", "back", "chest", "shirt", "tabard", "wrist" ]
    @right_column_gear  = ["hands", "waist", "legs", "feet", "finger1", "finger2", "trinket1", "trinket2" ]
    @mainhand           = [ "mainHand", "offHand" ] 
  end

  def get_standing(standing)
    case standing
    when 0
      "Hated"
    when 1
      "Acquaintance"
    when 2
      "Unfriendly"
    when 3
      "Neutral"
    when 4
      "Friendly"
    when 5
      "Honored"
    when 6
      "Revered"
    when 7
      "Exalted"
    else
      "Error"
    end
  end
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController
  helper_method :get_guild_name, :get_guild_member_count, :get_guild_description, :get_news_feed
  def index
    #
  end

  def show
    @nav_elements   = [ "Summary", "Roster", "News", "Achievements", "Challenge Mode" ]
    client         = BattleMuffin.new("7argtwb4rtuy2ccwcfjs74eapm52juhv") 
    @guild_name     = params[:id].split("_").first.strip
    @realm          = params[:id].split("_").last.strip
    @guild          = client.guild_handler.search(@realm, @guild_name)
    @all_info       = @guild.all_info
  end

  def get_guild_name
    if @guild.name.include?("%20")
      return @guild.name.gsub!("%20", " ")
    else
      return @guild.name
    end
  end

  def get_guild_member_count
    @all_info['members'].count
  end

  def get_guild_description
    "#{get_side} Guild, #{@realm}. #{get_guild_member_count} members"
  end

  def get_side
    if @guild.side == 1
      "Horde"
    else
      "Alliance"
    end
  end

  def get_item_description(id)
    Nokogiri::XML(HTTParty.get("http://www.wowhead.com/item=#{id}&xml").body).css('name').children.text
  end

  def get_news_feed
    feed = [ ]
    @all_info['news'].first(25).each do |item|
      result = { }
      result['character'] = item['character']
      if item['type'] == 'itemLoot'
        result['string'] = " obtained"
        result['link'] = get_item_description(item['itemId'])
        result['item_id'] = item['itemId']
      elsif item['type'] == 'playerAchievement'
        result['string'] = " earned the achievement "
        result['link'] = "#{item['achievement']['title']} for #{item['achievement']['points']} points"
      elsif item['type'] == 'itemPurchase'
        result['string'] = " purchased item"
        result['link'] = get_item_description(item['itemId'])
        result['item_id'] = item['itemId']
      elsif item['type'] == 'itemCraft'
        result['string'] = " crafted item"
        result['link'] = get_item_description(item['itemId'])
        result['item_id'] = item['itemId']
      end
      feed << result
    end
    feed
  end
end

app/controllers/search_controller.rb
def new
  @search = Search.new
end

def create
  @search = Search.new(params[:search])

  # TODO: use the @search object to perform a search.  Adding
  #   # a `results` method on the search object might be a good starting point.
end
#  = simple_form_for(@search) do |f|
#    = f.error_notification
#    .form-inputs
#      = f.input :character_name
#      = f.input :realm
#    .form-actions
#      = f.button :submit

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/guild_helper.rb
module GuildHelper
end

app/views/characters/_header.html.haml
#character_header
  #character_header_left
    #character_header_left_top
      #character_name
        = name
      #guild_title
        #title
          = @title
        #guild
          = link_to get_guild, guild_path(id: "#{get_guild}_#{@realm}")
    #character_header_left_bottom
      = build_stats_string
  #character_header_right
    #average_items_number
      = average_item_level
    #average_item_equipped
      #average_item_header
        average item level
      #average_item_equipped_value
        = "(#{average_item_level_equipped} equipped)"

app/views/characters/_nav.html.haml
#left_nav_bar
  #achievement_points
    = image_tag "http://us.battle.net/wow/static/images/icons/achievements.gif", {style: "float: left; padding-top: 10px; padding-right: 5px" }
    = achievement_points 
  #left_nav_bar_main
    %ul#link_styling
      %li= link_to 'Summary',         view_characters_path(character: { name: @character.name, realm: @realm }  )
      %li{style: "color: grey"} Hunter Pets
      %li{style: "color: grey"} Auctions
      %li{style: "color: grey"} Events
      %li= link_to 'Achievements',    achievements_path(id: @character.name, character: { name: @character.name, realm: @realm }  )
      %li= link_to 'Challenge Mode',  challenge_mode_path(id: @character.name, character: { name: @character.name, realm: @realm }  )
      %li= link_to 'Pets & Mounts',   pets_mounts_path(id: @character.name, character: { name: @character.name, realm: @realm }  )
      %li= link_to 'Progression',     progression_path(id: @character.name, character: { name: @character.name, realm: @realm }  )
      %li= link_to 'Reputation',      reputation_path(id: @character.name, character: { name: @character.name, realm: @realm }  )
      -#%li= link_to 'PvP',             pvp_path(character: { name: @character.name, realm: @realm }  )
      -#%li= link_to 'Activity',        activity_path(character: { name: @character.name, realm: @realm }  )
      -#%li= link_to 'Feed',            feed_path(character: { name: @character.name, realm: @realm }  )
      -#%li= link_to 'Guild',           guild_path(character: { name: @character.name, realm: @realm }  )

app/views/characters/achievements.html.haml
#character_wrapper{style: "height: 1000px; "}
  = render partial: 'header'
  #character_main_div{style: "height: 1000px;"}
    = render partial: 'nav'
    #character_body
      #guild_main_frame_title
        Recent achievements
      %ul#link_styling
        - achievement_array.each do |ach|
          %li{style: "color: #C09A67"}
            Earned the achievement
            %a.q3{:href => "http://www.wowhead.com/achievement=#{ach[:id]}"}
              = ach[:name]
            on
            = ach[:timestamp]
          %hr

app/views/characters/challenge_mode.html.haml
#character_wrapper
  = render partial: 'header'
  #character_main_div
    = render partial: 'nav'
    #character_body

app/views/characters/index.html.haml
#character_wrapper
  %div{style: "padding-top: 50px; padding-left: 50px; padding-right: 50px; color: #7e3406; font-size: 20px"}
    %div{style: "padding-bottom: 10px" }
      Search for character by name and realm
      %hr
    %div{style: "padding-left: 50px; padding-right: 50px"}
      = form_for :character,  url: view_characters_path, method: :get do |f|
        = f.text_field :name, class: 'form-control', style: 'height: 50px; font-size: 20px', value: "Sovrano"
        = select('character', 'realm', get_realms, {}, class: 'form-control', select: "Mal'Ganis" )
        = f.submit "Search for character", class: 'btn btn-primary'

app/views/characters/pets_mounts.html.haml
#character_wrapper{style: "height: 1000px; "}
  = render partial: 'header'
  #character_main_div{style: "height: 1000px;"}
    = render partial: 'nav'
    #character_body
      #character_pets
        #guild_main_frame_title
          = "Pets collected (#{@all_info['pets']['collected'].count})"
        %ul#link_styling
          - @all_info['pets']['collected'].first(15).each do |pet|
            %li
              = image_tag get_icon_url(pet['icon']), {:style => "display: inline; padding-right: 5px; padding-bottom: 5px"} 
              = pet['name']
          \...
      #character_mounts
        #guild_main_frame_title
          = "Mounts collected (#{@all_info['mounts']['collected'].count})"
        %ul#link_styling
          - @all_info['mounts']['collected'].first(15).each do |mount|
            %li
              = image_tag get_icon_url(mount['icon']), {:style => "display: inline; padding-right: 5px; padding-bottom: 5px"} 
              = mount['name']
          \...

app/views/characters/progression.html.haml
#character_wrapper{style: "height: 1000px; "}
  = render partial: 'header'
  #character_main_div{style: "height: 1000px;"}
    = render partial: 'nav'
    #character_body{style: "color: 7e3406;"}
      #guild_main_frame_title
        Raid Progression 
      %table.table.table-hover{style: "color: #7e3406;"}
        %thead
          %tr
            %th
            %th LFR
            %th Normal
            %th Heroic
            %th Mythic
        %tbody
          - @all_info['progression']['raids'].reverse.each do |progression|
            %tr 
              %td= progression['name']
              %td= progression['lfr']
              %td= progression['normal']
              %td= progression['heroic']
              %td= progression['mythic']

app/views/characters/reputation.html.haml
#character_wrapper{style: "height: 1000px; "}
  = render partial: 'header'
  #character_main_div{style: "height: 1000px;"}
    = render partial: 'nav'
    #character_body
      #guild_main_frame_title
        Reputation
      %ul#link_styling
        - @all_info['reputation'].sort_by { |hsh| hsh['standing'] }.reverse.each  do |rep|
          %li{style: "color: #C09A67"}
            = "#{rep['name']} - #{get_standing(rep['standing'])}"
            .progress
              .progress-bar{"aria-valuemax" => rep['max'], "aria-valuemin" => "0", "aria-valuenow" => rep['value'], :role => "progressbar", style: "min-width: 2em; width: #{((rep['value'].to_f / rep['max'].to_f)*100).to_i}%;"}
                = "#{rep['value']} / #{rep['max']}"
          %hr

app/views/characters/show.html.haml
#character_wrapper{:style => "background-image: url(#{get_background});"}
  = render partial: 'header'
  #character_main_div
    = render partial: 'nav'
    #character_image{:style => "background-image: url(#{get_profile_main});"}
      #gear_left_column
        -@left_column_gear.each do |gear|
          %ul.gear_column
            %li
              %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                = image_tag get_item_url(gear), {:style => "border-radius: 10px; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px; "} 
      #gear_buffer
        #mainhand_gear_buffer
        #mainhand_gear_footer
          -@mainhand.each do |gear|
            %ul#mainhand_gear_position
              %li{:style => "display: inline"}
                %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                  = image_tag get_item_url(gear), {:style => "border-radius: 10px; display: inline; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px;"} 
      #gear_right_column
        -@right_column_gear.each do |gear|
          %ul.gear_column
            %li
              %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                = image_tag get_item_url(gear), {:style => "border-radius: 10px; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px; "}

app/views/characters/view.html.haml
#character_wrapper{:style => "background-image: url(#{get_background});"}
  = render partial: 'header'
  #character_main_div
    = render partial: 'nav'
    #character_image{:style => "background-image: url(#{get_profile_main});"}
      #gear_left_column
        -@left_column_gear.each do |gear|
          %ul.gear_column
            %li
              %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                = image_tag get_item_url(gear), {:style => "border-radius: 10px; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px; "} 
      #gear_buffer
        #mainhand_gear_buffer
        #mainhand_gear_footer
          -@mainhand.each do |gear|
            %ul#mainhand_gear_position
              %li{:style => "display: inline"}
                %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                  = image_tag get_item_url(gear), {:style => "border-radius: 10px; display: inline; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px;"} 
      #gear_right_column
        -@right_column_gear.each do |gear|
          %ul.gear_column
            %li
              %a.q3{:href => "http://www.wowhead.com/item=#{get_item_id(gear)}", rel: "item=#{get_item_id(gear)}"}
                = image_tag get_item_url(gear), {:style => "border-radius: 10px; box-shadow: 7px 7px 5px #000000; border: solid; border-color: purple; border-width: 2px; "}